[package]
name = "host"
version = "0.1.0"
edition = "2021"

[dependencies]
zk-img-methods = { path = "../methods" }
risc0-zkvm = { version = "1.2.5" }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
serde = "1.0"
image = "0.24"  
sha2 = "0.10"   
bincode = "1.3"