[package]
name = "zk-img-method"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "1.2.5", default-features = false, features = ['std'] }
image = "0.24"
sha2 = "0.10"              
hex = "0.4"
