[package]
name = "composition"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "1.2.5", default-features = false, features = ['std'] }
zk-img-methods = {path = "../../../imgTransformations/methods"}
image = "0.25"
